import Link from "next/link";
import { BrandLogo } from "@/components/brand-logo";

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen flex-col">
      <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur">
        <div className="mx-auto flex h-14 max-w-5xl items-center justify-between px-4">
          <Link href="/" className="flex items-center gap-2">
            <BrandLogo />
            <span className="font-semibold">avenora</span>
          </Link>
          <nav className="flex items-center gap-4 text-sm">
            <Link
              href="/signin"
              className="text-muted-foreground hover:text-foreground"
            >
              Sign in
            </Link>
            <Link
              href="/signup"
              className="text-muted-foreground hover:text-foreground"
            >
              Sign up
            </Link>
          </nav>
        </div>
      </header>
      <main className="flex-1">{children}</main>
      <footer className="border-t py-6 text-center text-sm text-muted-foreground">
        avenora — generated by starter-gen
      </footer>
    </div>
  );
}
