import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function Home() {
  return (
    <section className="mx-auto flex max-w-5xl flex-col items-center gap-6 px-4 py-24 text-center">
      <h1 className="text-4xl font-bold tracking-tight sm:text-6xl">avenora</h1>
      <p className="max-w-2xl text-lg text-muted-foreground">
        A Next.js starter with Better Auth, tRPC, Prisma, and Tailwind CSS —
        generated by starter-gen.
      </p>
      <div className="flex gap-4">
        <Button asChild size="lg">
          <Link href="/signup">Get started</Link>
        </Button>
        <Button asChild size="lg" variant="outline">
          <Link href="/signin">Sign in</Link>
        </Button>
      </div>
    </section>
  );
}
